config/routes.rb
Rails.application.routes.draw do
  get "post_saves/index"
  get "groups/index"
  get "groups/show"
  get "groups/edit"
  get "categories/index"
  devise_for :users
  root to: "homes#top"
  get "about", to: "homes#about", as: "about"
  get "index", to: "homes#index", as: "index"
  resources :users, only: [:edit, :update, :show, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
    get "index", to: "users#post_index", as: "post_index"
    get "chats", to: "chats#index", as: "chats"
    get "saves", to: "post_saves#index", as: "saves"
  end
  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :recommend_place_posts do
    resource :post_favorite, only: [:create, :destroy]
    resource :post_saves, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy] do
      resource :comment_favorite, only: [:create, :destroy]
    end
  end
  get "searches/result", to: "searches#search", as: "search"
  get "searches/new", to: "searches#new", as: "new_search"
  resources :chats, only: [:create, :show, :destroy]
  resources :notifications, only: [:update]
  resources :categories, only: [:index, :create] do
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:destroy]
      resources :group_comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  include Notifiable

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  has_one :notification, as: :notifiable, dependent: :destroy

  after_create do
    create_notification(user_id: followed_id)
  end

  def notification_message
    "#{follower.nick_name}さんにフォローされました。"
  end

  def notification_path
    user_path(follower_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings.page(params[:page])
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers.page(params[:page])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, remote:true, data: {"turbolinks" => false}, class: 'btn sm-btn unfollow-btn' %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, remote:true, data: {"turbolinks" => false}, class: 'btn sm-btn follow-btn' %>
  <% end %>
<% end %>

app/views/relationships/_btn_follow.html.erb
<%= link_to 'フォローする', user_relationships_path(user.id), method: :post, remote:true, data: {"turbolinks" => false}, class: 'btn sm-btn follow-btn' %>

app/views/relationships/_btn_unfollow.html.erb
<%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, remote:true, data: {"turbolinks" => false}, class: 'btn sm-btn unfollow-btn' %>

app/views/relationships/_count.html.erb
<p>
  <%= link_to user_followings_path(user) do %>
    follows: <%= user.followings.count %>人
  <% end %>
</p>
<p>
  <%= link_to user_followers_path(user) do %>
    followers: <%= user.followers.count %>人
  <% end %>
</p>

app/views/relationships/create.js.erb
$('#relationship-count').html("<%= j(render 'relationships/count', user: @user) %>");
$('#relationship-btn').html("<%= j(render 'relationships/btn_unfollow', user: @user) %>");

app/views/relationships/destroy.js.erb
$('#relationship-count').html("<%= j(render 'relationships/count', user: @user) %>");
$('#relationship-btn').html("<%= j(render 'relationships/btn_follow', user: @user) %>");

app/views/relationships/followers.html.erb
<div class='main-wrapper'>
  <h2><%= @user.nick_name %>さんのフォロワー</h2>
  <div class='content-wrapper'>
    <%= link_to 'ユーザーページへ戻る', user_path(@user), class: 'btn btn-sm back-btn' %>
    <% if @users.exists? %>
      <div class='d-flex flex-wrap mt-5'>
        <%= render 'users/index', users: @users %>
      </div>
    <% else %>
      <p>ユーザーはいません。</p>
    <% end %>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class='main-wrapper'>
  <h2><%= @user.nick_name %>さんのフォローユーザー</h2>
  <div class='content-wrapper'>
    <%= link_to 'ユーザーページへ戻る', user_path(@user), class: 'btn btn-sm back-btn' %>
    <% if @users.exists? %>
      <div class='d-flex flex-wrap mt-5'>
        <%= render 'users/index', users: @users %>
      </div>
    <% else %>
      <p>ユーザーはいません。</p>
    <% end %>
  </div>
</div>