config/routes.rb
Rails.application.routes.draw do
  get "post_saves/index"
  get "groups/index"
  get "groups/show"
  get "groups/edit"
  get "categories/index"
  devise_for :users
  root to: "homes#top"
  get "about", to: "homes#about", as: "about"
  get "index", to: "homes#index", as: "index"
  resources :users, only: [:edit, :update, :show, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
    get "index", to: "users#post_index", as: "post_index"
    get "chats", to: "chats#index", as: "chats"
    get "saves", to: "post_saves#index", as: "saves"
  end
  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :recommend_place_posts do
    resource :post_favorite, only: [:create, :destroy]
    resource :post_saves, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy] do
      resource :comment_favorite, only: [:create, :destroy]
    end
  end
  get "searches/result", to: "searches#search", as: "search"
  get "searches/new", to: "searches#new", as: "new_search"
  resources :chats, only: [:create, :show, :destroy]
  resources :notifications, only: [:update]
  resources :categories, only: [:index, :create] do
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:destroy]
      resources :group_comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_categories, dependent: :destroy
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_many :users, through: :group_users
  has_many :group_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, presence: true, length: { maximum: 100 }

  has_one_attached :group_image

  def is_owned_by?(user)
    owner.id == user.id
  end

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join("app/assets/images/no-group-img.jpg")
      group_image.attach(io: File.open(file_path), filename: "default-group-image.jpg", content_type: "image/jpeg")
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  def includes_user?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def new
    @category = Category.find(params[:category_id])
    @group = Group.new
  end
  def create
    category = Category.find(params[:category_id])
    @group = category.groups.new(group_params)
    if @group.save
      GroupCategory.create(category_id: category.id, group_id: @group.id)
      redirect_to category_group_path(category.id, @group.id), notice: "新しく表題が作成されました。"
    else
      render :new
    end
  end

  def index
    @category = Category.find(params[:category_id])
    @groups = @category.groups
  end

  def show
    @category = Category.find(params[:category_id])
    @group = Group.find(params[:id])
    @group_comment = @group.group_comments.new
    unless @group.includes_user?(current_user)
      current_user.group_users.create(group_id: params[:id])
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @group = Group.find(params[:id])
  end

  def update
    category = Category.find(params[:category_id])
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to category_group_path(category.id, @group.id), notice: "表題の内容が更新されました。"
    else
      render :edit
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    redirect_to categories_path
  end

  private
    def ensure_correct_user
      group = Group.find(params[:id])
      unless group.owner_id == current_user.id
        redirect_to category_groups_path
      end
    end

    def group_params
      params.require(:group).permit(:name, :introduction, :owner_id, :group_image)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: [category, group] do |f| %>
  <%= f.hidden_field :owner_id, :value => current_user.id %>
  <div class='form-group'>
    <label>表題：</label><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label>表題の説明：</label><br>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label>表題に基づく画像</label><br>
    <%= f.file_field :group_image, accept: 'images/*', class: 'd-block' %>
  </div>
  <div class='form-group'>
    <%= f.submit btn, class: 'btn btn-sm submit-btn' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='main-wrapper'>
  <h2>表題編集画面</h2>
  <div class='content-wrapper'>
    <%= render 'groups/form', category: @category, group: @group, btn: '更新' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='main-wrapper'>
  <h2>カテゴリー「<%= @category.name %>」の表題一覧</h2>
  <div class='content-wrapper'>
    <%= link_to '新しく表題を作る', new_category_group_path(@category.id), class: 'btn btn-sm new-group-btn' %>
    <%= link_to 'カテゴリーに戻る', categories_path, class: 'btn btn-sm back-btn' %>
    <hr class='my-5'>
    <% @groups.each do |group| %>
      <p><%= group.name %></p>
      <small><%= group.introduction %></small><br>
      <%= link_to category_group_path(@category.id, group.id), class: 'btn btn-sm submit-btn mt-2' do %>
        <% if group.is_owned_by?(current_user) %>
          自分が作成した表題
        <% elsif group.includes_user?(current_user) %>
          参加中
        <% else %>
          この表題に参加
        <% end %>
      <% end %><br>
      <small><%= group.users.count %>名が参加中</small>
      <hr class='my-5'>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class='main-wrapper'>
  <h2>新規表題作成</h2>
  <div class='content-wrapper'>
    <%= render 'groups/form', category: @category, group: @group, btn: '作成' %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='main-wrapper'>
  <div class='content-wrapper'>
    <div class='p-3'>
      <small><%= @group.owner.nick_name %>さんより、</small>
      <p>表題：<%= @group.name %></p>
      <%= image_tag @group.get_group_image(200,200) %>
      <p><%= @group.introduction %></p>
      <hr>
      参加者:
      <% @group.users.each do |user| %>
        <%= link_to user_path(user.id) do %>
          <%= image_tag user.get_profile_image(20,20), class: 'rounded-circle' %>
        <% end %>
      <% end %>
      <hr>
      <%= link_to '表題一覧へ戻る', category_groups_path(@category.id), class: 'btn btn-sm back-btn' %>
      <% if @group.is_owned_by?(current_user) %>
        <%= link_to '編集する', edit_category_group_path(@category.id, @group.id), class: 'btn btn-sm edit-btn' %>
        <%= link_to 'この表題グループを削除する', category_group_path(@category.id, @group.id), method: :delete, class: 'btn btn-sm destroy-btn' %>
      <% else %>
        <%= link_to 'この表題から参加を外れる', category_group_group_users_path(@category.id, @group.id), method: :delete, class: 'btn btn-sm destroy-btn' %>
      <% end %>
      <hr>
    </div>
    <div>
      <%= form_with model: [@category, @group, @group_comment] do |f| %>
        <%= f.text_area :comment, class: 'form-control' %>
        <%= f.submit '意見コメント', class: 'btn btn-sm submit-btn mt-2' %>
      <% end %>
      <hr>
      <div>
        <%= render 'group_comments/index', group: @group, category: @category %>
      </div>
    </div>
  </div>
</div>