config/routes.rb
Rails.application.routes.draw do
  get "post_saves/index"
  get "groups/index"
  get "groups/show"
  get "groups/edit"
  get "categories/index"
  devise_for :users
  root to: "homes#top"
  get "about", to: "homes#about", as: "about"
  get "index", to: "homes#index", as: "index"
  resources :users, only: [:edit, :update, :show, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
    get "index", to: "users#post_index", as: "post_index"
    get "chats", to: "chats#index", as: "chats"
    get "saves", to: "post_saves#index", as: "saves"
  end
  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :recommend_place_posts do
    resource :post_favorite, only: [:create, :destroy]
    resource :post_saves, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy] do
      resource :comment_favorite, only: [:create, :destroy]
    end
  end
  get "searches/result", to: "searches#search", as: "search"
  get "searches/new", to: "searches#new", as: "new_search"
  resources :chats, only: [:create, :show, :destroy]
  resources :notifications, only: [:update]
  resources :categories, only: [:index, :create] do
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:destroy]
      resources :group_comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :recommend_place_posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_favorites, dependent: :destroy
  has_many :comment_favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :post_view_counts, dependent: :destroy

  has_many :active_views, class_name: "ProfileViewCount", foreign_key: "viewer_id", dependent: :destroy
  has_many :passive_views, class_name: "ProfileViewCount", foreign_key: "viewed_id", dependent: :destroy
  has_many :profile_viewers, through: :passive_views, source: :viewer

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :notifications, dependent: :destroy

  has_many :group_users, dependent: :destroy
  has_many :group_comments, dependent: :destroy

  has_many :post_saves, dependent: :destroy
  has_many :saved_posts, through: :post_saves, source: :recommend_place_post

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }

  validates :name, presence: true
  validates :nick_name, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  validates :role, presence: true

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.nick_name = "guest_user"
      user.role = "begginer"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def get_role
    if self.role == "beginner"
      "初心者"
    elsif self.role == "intermediate"
      "中級者"
    else
      "ベテラン"
    end
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method, select_role)
    if method == "perfect"
      User.where(nick_name: content, role: select_role)
    else
      User.where(role: select_role).where("nick_name LIKE?", "%" + content + "%")
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]
  before_action :ensure_correct_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "プロフィール情報を更新しました。"
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    unless ProfileViewCount.where(created_at: Time.zone.now.all_day).find_by(viewer_id: current_user.id, viewed_id: @user.id)
      current_user.active_views.create(viewed_id: @user.id)
    end
  end

  def index
    if params[:latest]
      @users = User.latest.page(params[:page])
    elsif params[:old]
      @users = User.old.page(params[:page])
    else
      @users = User.all.page(params[:page])
    end
  end

  def post_index
    @user = User.find(params[:user_id])
    @recommend_place_posts = @user.recommend_place_posts.page(params[:page])
  end

  private
    def user_params
      params.require(:user).permit(:name, :nick_name, :email, :introduction, :profile_image, :role)
    end

    def ensure_guest_user
      user = User.find(params[:id])
      if user.guest_user?
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end

    def ensure_correct_user
      user = User.find(params[:id])
      unless user.id == current_user.id
        redirect_to index_path, caution: "他人のユーザー情報は編集できません。"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% users.each do |user| %>
  <%= link_to user_path(user) do %>
    <div class='card user-card'>
      <%= image_tag user.get_profile_image(150,150), class: 'img-profile' %>
      <div class='card-body user-card-body'>
        <h5 class='card-title'>
          <span class='btn btn-sm role-btn'><%= user.get_role %></span>
          <p><%= user.nick_name %></p>
        </h5>
        <p class='card-text'><%= user.introduction %></p>
      </div>
    </div>
  <% end %>
<% end %>
<%= paginate users %>

app/views/users/edit.html.erb
<div class='main-wrapper'>
  <h2>プロフィール編集フォーム</h2>
  <div class='content-wrapper'>
    <%= render 'layouts/errors', obj: @user %>
    <%= form_with model: @user do |f| %>
      <div class='form-group'>
        <%= f.label :name %></br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :nick_name %></br>
        <%= f.text_field :nick_name, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :email %></br>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :introduction %></br>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :image %></br>
        <%= f.file_field :profile_image, class: 'd-block', accept: 'images/*' %> 
      </div>
      <div class='form-group'>
        <%= f.submit '更新', class: 'btn btn-sm btn-success' %>
      </div>
    <% end %>
    <%= link_to 'マイページに戻る', user_path(current_user), class: 'btn sm-btn back-btn' %>
  </div>
</div>

app/views/users/index.html.erb
<div class='main-wrapper'>
  <h2>ユーザー一覧</h2>
  <div class='content-wrapper'>
    <%= render 'searches/form_user' %>
    <p><%= link_to '登録が新しい順', users_path(latest: true) %>
      |<%= link_to '登録が古い順', users_path(old: true) %></p>
    <div class='d-flex flex-wrap mt-5'>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/post_index.html.erb
<div class='main-wrapper'>
  <h2><%= @user.nick_name %>さんの投稿一覧</h2>
  <div class='content-wrapper'>
    <div class='d-flex flex-wrap mt-5'>
      <%= render 'recommend_place_posts/index', posts: @recommend_place_posts %>
    </div>
    <%= link_to 'ユーザー詳細画面に戻る', user_path(@user), class: 'btn btn-sm back-btn' %>
  </div>
</div>

app/views/users/show.html.erb
<div class='main-wrapper'>
  <% if @user == current_user %>
    <h2>マイページ<small>　/ニックネーム: <%= @user.nick_name %></small></h2>
  <% else %>
    <h2><%= @user.nick_name %>さんのプロフィール</h2>
  <% end %>
  <div class='content-wrapper'>
    <p><i class="fa-solid fa-chart-simple"></i> 閲覧された回数：<%= @user.profile_viewers.count %>回</p>
    <div class='mb-5'>
      <%= image_tag @user.get_profile_image(200,200) %>
      <div class='relationship-box'>
        <div id='relationship-count'>
        <%= render 'relationships/count', user: @user %>
        </div>
        <div id='relationship-btn'>
          <%= render 'relationships/btn', user: @user %>
        </div>
      </div>
    </div>
    <p>私は、日本生活の<%= @user.get_role %>です。</p>
    <hr>
    <p><%= @user.introduction %></p>
    <hr>
    <div class='mt-5'>
      <% if @user == current_user %>
        <%= link_to 'プロフィール編集', edit_user_path(current_user), class: 'btn btn-sm btn-secondary' %>
      <% end %>
      <% unless @user == current_user %>
        <%= link_to 'このユーザーとのトークルーム', chat_path(@user.id), class: 'btn btn-sm chat-btn' %>
      <% end %>
      <hr>
      <%= link_to 'このユーザーの投稿一覧', user_post_index_path(@user), class: 'btn btn-sm submit-btn' %>
      <%= link_to 'ユーザー一覧に戻る', users_path, class: 'btn btn-sm back-btn' %>
    </div>
    
    
    <!--このユーザーの意見一覧-->
  </div>
</div>