config/routes.rb
Rails.application.routes.draw do
  get "post_saves/index"
  get "groups/index"
  get "groups/show"
  get "groups/edit"
  get "categories/index"
  devise_for :users
  root to: "homes#top"
  get "about", to: "homes#about", as: "about"
  get "index", to: "homes#index", as: "index"
  resources :users, only: [:edit, :update, :show, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings", to: "relationships#followings", as: "followings"
    get "followers", to: "relationships#followers", as: "followers"
    get "index", to: "users#post_index", as: "post_index"
    get "chats", to: "chats#index", as: "chats"
    get "saves", to: "post_saves#index", as: "saves"
  end
  devise_scope :user do
    post "users_guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :recommend_place_posts do
    resource :post_favorite, only: [:create, :destroy]
    resource :post_saves, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy] do
      resource :comment_favorite, only: [:create, :destroy]
    end
  end
  get "searches/result", to: "searches#search", as: "search"
  get "searches/new", to: "searches#new", as: "new_search"
  resources :chats, only: [:create, :show, :destroy]
  resources :notifications, only: [:update]
  resources :categories, only: [:index, :create] do
    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :group_users, only: [:destroy]
      resources :group_comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recommend_place_post.rb
class RecommendPlacePost < ApplicationRecord
  include Notifiable

  has_one_attached :post_image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :post_favorites, dependent: :destroy
  has_many :post_view_counts, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  has_many :notifications, as: :notifiable, dependent: :destroy

  has_many :post_saves, dependent: :destroy

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }

  validates :name, presence: true
  validates :caption, length: { maximum: 20 }
  validates :introduction, length: { maximum: 2000 }
  validates :prefecture, presence: true

  enum prefecture: {
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47, その他: 48, 指定しない: 49
  }

  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join("app/assets/images/no-post-image.png")
      post_image.attach(io: File.open(file_path), filename: "default-post-image.png", content_type: "image/png")
    end
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    post_favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method, prefecture_number, subject)
    if method == "perfect"
      if subject == "name"
        records = RecommendPlacePost.where(name: content)
      elsif subject == "caption"
        records = RecommendPlacePost.where(caption: content)
      else
        records = RecommendPlacePost.where(introduction: content)
      end
      unless prefecture_number == 49
        records = records.where(prefecture: prefecture_number)
      end
      records
    else
      if subject == "name"
        records = RecommendPlacePost.where("name LIKE?", "%" + content + "%")
      elsif subject == "caption"
        records = RecommendPlacePost.where("caption LIKE?", "%" + content + "%")
      else
        records = RecommendPlacePost.where("introduction LIKE?", "%" + content + "%")
      end
      unless prefecture_number == 49
        records = records.where(prefecture: prefecture_number)
      end
      records
    end
  end

  def save_tags(savepost_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      self.tags << post_tag
    end
  end

  after_create do
    records = user.followers.map do |follower|
      notifications.new(user_id: follower.id)
    end
    Notification.import records
  end

  def notification_message
    "フォローしている#{user.nick_name}さんが新規投稿しました。"
  end

  def notification_path
    recommend_place_post_path(self)
  end

  def post_saved_by?(user)
    post_saves.exists?(user_id: user.id)
  end
end

app/controllers/recommend_place_posts_controller.rb
class RecommendPlacePostsController < ApplicationController
  before_action :ensure_matching_author, only: [:edit, :update, :destroy]

  def new
    @recommend_place_post = RecommendPlacePost.new
    @prefectures = RecommendPlacePost.prefectures
  end

  def create
    @recommend_place_post = current_user.recommend_place_posts.new(recommend_place_post_params)
    tag_list = params[:recommend_place_post][:tag_name].split(",")
    if @recommend_place_post.save
      @recommend_place_post.save_tags(tag_list)
      redirect_to recommend_place_post_path(@recommend_place_post.id), notice: "新規投稿されました。"
    else
      render :new
    end
  end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    if params[:latest]
      @recommend_place_posts = RecommendPlacePost.latest.page(params[:page])
    elsif params[:old]
      @recommend_place_posts = RecommendPlacePost.old.page(params[:page])
    else
      @recommend_place_posts = RecommendPlacePost.all.sort { |a, b|
        b.post_favorites.where(created_at: from...to).size <=>
        a.post_favorites.where(created_at: from...to).size
      }
      @recommend_place_posts = Kaminari.paginate_array(@recommend_place_posts).page(params[:page])
    end
    @prefectures = RecommendPlacePost.prefectures
  end

  def show
    @recommend_place_post = RecommendPlacePost.find(params[:id])
    @post_comment = PostComment.new
    unless PostViewCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, recommend_place_post_id: @recommend_place_post.id)
      current_user.post_view_counts.create(recommend_place_post_id: @recommend_place_post.id)
    end
  end

  def edit
    @recommend_place_post = RecommendPlacePost.find(params[:id])
    @prefectures = RecommendPlacePost.prefectures
  end

  def update
    recommend_place_post = RecommendPlacePost.find(params[:id])
    tag_list = params[:recommend_place_post][:tag_name].split(",")
    if recommend_place_post.update(recommend_place_post_params)
      recommend_place_post.save_tags(tag_list)
      redirect_to recommend_place_post_path(recommend_place_post.id), notice: "投稿が更新されました。"
    else
      render :edit
    end
  end

  def destroy
    RecommendPlacePost.find(params[:id]).destroy
    redirect_to recommend_place_posts_path, notice: "投稿を削除しました。"
  end

  private
    def recommend_place_post_params
      params.require(:recommend_place_post).permit(:name, :caption, :introduction, :post_image).merge(prefecture: params[:recommend_place_post][:prefecture].to_i)
    end

    def ensure_matching_author
      unless current_user.id == RecommendPlacePost.find(params[:id]).user_id
        redirect_to recommend_place_posts_path, caution: "他人の投稿は編集できません。"
      end
    end
end

app/helpers/recommend_place_posts_helper.rb
module RecommendPlacePostsHelper
end

app/views/recommend_place_posts/_form.html.erb
<%= form_with model: recommend_place_post do |f| %>
  <div class='form-group'>
    <%= f.label :image %>
    <%= f.file_field :post_image, accept: 'images/*', class: 'd-block' %>
  </div>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :caption %>
    <%= f.text_area :caption, maxlength: 20, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :prefecture %>
    <%= f.select :prefecture, options_for_select(prefectures), class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :tag %><span>※複数入力する場合は、スペースは空けずに「,」で区切ってください。</span>
    <%= f.text_field :tag_name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :introduction %>
    <%= f.text_area :introduction, size: ' 20 x 30 ', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.submit btn, class: 'btn submit-btn' %>
  </div>
<% end %>

app/views/recommend_place_posts/_index.html.erb
<% posts.each do |post| %>
  <%= link_to recommend_place_post_path(post.id) do %>
    <div class='card post-card'>
      <sm class='ml-auto mr-3'><i class="fa-solid fa-chart-simple"></i> <%= post.post_view_counts.count %></sm>
      <%= image_tag post.get_post_image(200,150), class: 'img-post' %>
      <div class='card-body post-card-body'>
        <h5 class='card-title'><%= post.name %></h5>
        <p><%= post.caption %></p>
      </div>
    </div>
  <% end %>
<% end %>
<%= paginate posts %>

app/views/recommend_place_posts/edit.html.erb
<div class='main-wrapper'>
  <h2>日本のおすすめ投稿編集</h2>
  <div class='content-wrapper'>
    <%= render 'form', recommend_place_post: @recommend_place_post, prefectures: @prefectures, btn: '更新' %>
  </div>
</div>

app/views/recommend_place_posts/index.html.erb
<div class='main-wrapper'>
  <h2>日本のおすすめ投稿一覧</h2>
  <div class='content-wrapper'>
    <%= link_to '新規投稿する', new_recommend_place_post_path, class: 'btn submit-btn' %>
    <%= link_to user_saves_path(current_user), class: 'btn btn-sm' do %>
      <i class="fa-solid fa-bookmark"></i>保存一覧
    <% end %>
    <%= render 'searches/form_posts', prefectures: @prefectures %>
    <p>
      <%= link_to '投稿日が新しい順', recommend_place_posts_path(latest: true) %>
      |<%= link_to '投稿日が古い順', recommend_place_posts_path(old: true) %>
      |<%= link_to '直近１週間のいいね多い順', recommend_place_posts_path %>
    </p>
    <div class='d-flex flex-wrap mt-5'>
      <%= render 'index', posts: @recommend_place_posts %>
    </div>
  </div>
</div>

app/views/recommend_place_posts/new.html.erb
<div class='main-wrapper'>
  <h2>日本のおすすめ新規投稿</h2>
  <div class='content-wrapper'>
    <%= render 'form', recommend_place_post: @recommend_place_post, prefectures: @prefectures, btn: '新規投稿' %>
    <%= link_to 'おすすめ投稿一覧に戻る', recommend_place_posts_path, class: 'btn btn-sm back-btn' %>
  </div>
</div>

app/views/recommend_place_posts/show.html.erb
<div class='main-wrapper'>
  <h2>日本のおすすめ投稿詳細</h2>
  <%= link_to 'おすすめ投稿一覧に戻る', recommend_place_posts_path, class: 'btn btn-sm back-btn' %>
  <div class='content-wrapper'>
    <h3><%= @recommend_place_post.name %></h3>
    <span><%= @recommend_place_post.prefecture %></span>
    <% if current_user != @recommend_place_post.user %>
      <% if @recommend_place_post.post_saved_by?(current_user) %>
        <%= link_to recommend_place_post_post_saves_path(@recommend_place_post), method: :delete do %>
          <i class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= link_to recommend_place_post_post_saves_path(@recommend_place_post), method: :post do %>
          <i class="fa-regular fa-bookmark"></i>
        <% end %>
      <% end %>
    <% end %>
    <p><%= @recommend_place_post.caption %></p>
    <span class='mr-3'>投稿日： <%= @recommend_place_post.created_at.strftime('%Y/%m/%d') %></span>
    <span class='mr-3' id='post-favorite'><%= render 'post_favorites/btn', recommend_place_post: @recommend_place_post %></span>
    <span class='ml-auto mr-3'><i class="fa-solid fa-chart-simple"></i> 閲覧数：<%= @recommend_place_post.post_view_counts.count %>回</span>
    <hr>
    <div>
      <%= image_tag @recommend_place_post.get_post_image(200,200) %>
      <div>
        <% if @recommend_place_post.tags.exists? %>
          <% @recommend_place_post.tags.each do |tag| %>
            <%= link_to search_path( :model => 'tag', :method => 'perfect', :content => tag.name), class: 'btn btn-sm tag-btn' do %>
              <i class="fa-solid fa-tag"></i><%= tag.name %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <p><%= @recommend_place_post.introduction %></p>
    </div>
    <hr>
    <div>
      <%= image_tag @recommend_place_post.user.get_profile_image(30,30) %>
      <%= link_to user_path(@recommend_place_post.user.id) do %>
        <p><i class="fa-solid fa-user-large"></i><%= @recommend_place_post.user.nick_name %>さん</p>
      <% end %>
      <p><i class="fa-solid fa-flag"></i>日本生活の<%= @recommend_place_post.user.role %></p>
    </div>

    <% if @recommend_place_post.user == current_user %>
      <%= link_to '編集する', edit_recommend_place_post_path(@recommend_place_post.id), class: 'btn btn-sm edit-btn' %>
      <%= link_to '削除する', recommend_place_post_path(@recommend_place_post.id), method: :delete, class: 'btn btn-sm destroy-btn', 'data-confirm' => '本当に削除してもいいですか？' %>
    <% end %>
    
    <hr>
    <h4><i class="fa-regular fa-message"></i>コメント一覧</h4>
    <div id='post-comments'>
      <%= render 'post_comments/index', recommend_place_post: @recommend_place_post %>
    </div>
    <hr>
    <h4>コメント投稿</h4>
    <div>
      <%= render 'post_comments/form', recommend_place_post: @recommend_place_post, post_comment: @post_comment, btn: 'コメント投稿' %>
    </div>
  </div>
</div>